steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/avocado-manager-frontend:$SHORT_SHA', 'gcr.io/$PROJECT_ID/avocado-manager-frontend:$TAG_NAME' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/avocado-manager-frontend:$TAG_NAME']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/frontend', 'frontend=gcr.io/$PROJECT_ID/avocado-manager-frontend:$TAG_NAME']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-north1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'

images:
  - 'gcr.io/$PROJECT_ID/avocado-manager-frontend:$TAG_NAME'