steps:
- name: gcr.io/cloud-builders/mvn
  entrypoint: 'mvn'
  args: ['install', '--batch-mode', '-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN']
  dir: 'backend'
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/avocado-manager-backend:$SHORT_SHA', '-f', 'src/main/docker/Dockerfile.jvm', '.' ]
  dir: 'backend'
images:
  - 'gcr.io/$PROJECT_ID/avocado-manager-backend:$SHORT_SHA'
