steps:
- name: maven:3.6.0-jdk-11-slim
  entrypoint: 'mvn'
  args: ['install']
  dir: 'backend'
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/avocado-manager-backend', '-f', 'src/main/docker/Dockerfile.jvm', '.' ]
  dir: 'backend'
images:
  - 'gcr.io/$PROJECT_ID/avocado-manager-backend'
