apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: avocado-backend
  name: avocado-backend
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: avocado-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: avocado-backend
    spec:
      containers:
      - image: gcr.io/gke-lunch/avocado-manager-backend:074c198
        imagePullPolicy: IfNotPresent
        name: backend
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
      