apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: avocado-frontend
  name: avocado-frontend
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: avocado-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: avocado-frontend
    spec:
      containers:
      - env:
        - name: BACKEND_ROOT
          value: dummy
        image: gcr.io/gke-lunch/avocado-manager-frontend:cd5eff2
        imagePullPolicy: IfNotPresent
        name: frontend
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3